{% set name = "lenstronomy" %}
{% set version = "1.12.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lenstronomy-{{ version }}.tar.gz
  sha256: 640f8ca7e43e6fec18e8accb3e17e434a7e299f922e2fa7daba369072f4afe9f


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
  run:
    - astropy-base
    - configparser
    - corner >=2.2.1
    - h5py
    - matplotlib-base
    - mpmath
    - multiprocess >=0.70.8
    - numba >=0.43.1
    - numpy >=1.13
    - python >={{ python_min }}
    - pyxdg
    - pyyaml
    - schwimmbad
    - scikit-image
    - scikit-learn
    - scipy >=0.19.1

test:
  imports:
    - lenstronomy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lenstronomy/lenstronomy
  summary: Strong lens modeling package.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sibirrer
