{% set name = "lenstronomy" %}
{% set version = "1.12.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lenstronomy-{{ version }}.tar.gz
  sha256: 5433f5b67af89ddc98842d8c9c6f2f04e5018bb76f9c30d52cc2a9a09143d80d


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest
    - python >=3.7
  run:
    - astropy-base
    - configparser
    - corner >=2.2.1
    - h5py
    - matplotlib-base
    - mpmath
    - multiprocess >=0.70.8
    - numba >=0.43.1
    - numpy >=1.13
    - python >=3.7
    - pyxdg
    - pyyaml
    - schwimmbad
    - scikit-image
    - scikit-learn
    - scipy >=0.19.1

test:
  imports:
    - lenstronomy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lenstronomy/lenstronomy
  summary: Strong lens modeling package.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sibirrer
