{% set name = "lenstronomy" %}
{% set version = "1.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lenstronomy-{{ version }}.tar.gz
  sha256: e0b48ee0b9b0be2699c7e785672898413cbaaaa39dc84d0aab48d80e483316d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python >=3.7
  run:
    - astropy
    - configparser
    - corner >=2.2.1
    - h5py
    - matplotlib-base
    - mpmath
    - multiprocess >=0.70.8
    - numba >=0.43.1
    - numpy >=1.13
    - python >=3.7
    - pyxdg
    - pyyaml
    - schwimmbad
    - scikit-image
    - scikit-learn
    - scipy >=0.19.1

test:
  imports:
    - lenstronomy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sibirrer/lenstronomy
  summary: Strong lens modeling package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sibirrer
